MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
MONGODB_SET = '$set'
MONGODB_SET_ON_INSERT = '$setOnInsert'

DB_NAME = 'MangaSourcesFetcher'

MANGA_SOURCE_COLLECTIONS = 'sources'
MANGA_SOURCE_ID_FIELD = '_id'
MANGA_SOURCE_URL_FIELD = 'url'
MANGA_SOURCE_NAME_FIELD = 'name'
MANGA_SOURCE_QUERYURL_FIELD = 'queryURL'
MANGA_SOURCE_INSERTION_DATE_FIELD = 'insertionDate'
MANGA_SOURCE_LAST_UPDATE_FIELD = 'lastUpdateDate'

MANGA_COLLECTIONS = 'manga'
MANGA_ID_FIELD = '_id'
MANGA_NAMES_FIELD = 'names'
MANGA_INSERTION_DATE_FIELD = 'insertionDate'
MANGA_LAST_UPDATE_FIELD = 'lastUpdateDate'

MANGA_SOURCE_PAIR_COLLECTIONS = 'source_manga_pair'
MANGA_SOURCE_PAIR_MANGA_ID_FIELD = 'manga_id'
MANGA_SOURCE_PAIR_SOURCE_ID_FIELD = 'mangaSource_id'
MANGA_SOURCE_PAIR_URL_FIELD = 'url'
MANGA_SOURCE_PAIR_INSERTION_DATE_FIELD = 'insertionDate'
MANGA_SOURCE_PAIR_LAST_UPDATE_FIELD = 'lastUpdateDate'