MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
MONGODB_SET = '$set'
MONGODB_SET_ON_INSERT = '$setOnInsert'

DB_NAME = 'MangaSourcesFetcher'

MANGA_SOURCE_COLLECTIONS = 'sources'
MANGA_SOURCE_URL_FIELD = 'url'
MANGA_SOURCE_NAME_FIELD = 'name'
MANGA_SOURCE_QUERYURL_FIELD = 'queryURL'
MANGA_SOURCE_INSERTION_DATE_FIELD = 'insertionDate'
MANGA_SOURCE_LAST_UPDATE_FIELD = 'lastUpdateDate'

MANGA_NAME_COLLECTIONS = 'manga'